logging.level.root=INFO

# PostgreSQL database connection settings - using AWS Secrets Manager to retrieve credentials
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.show-sql=true
